# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 34.41.117.250
  become: yes

  tasks:
    - name: Call Roles
      hosts: 34.41.117.250
      roles:
        #- hostname
        #- firewalld
        #- ntp-config
        - motd
